AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  KnowledgeBaseId:
    Type: String
    NoEcho: true
  ModelArn:
    Type: String
    NoEcho: true

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 30
    MemorySize: 128

Resources:
  RagApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: rag-api-sam
      StageName: prod

      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,x-api-key'"
        AllowOrigin: "'*'"

  RagFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rag-api-sam

      CodeUri: src/

      Handler: index.handler

      Environment:
        Variables:
          KNOWLEDGE_BASE_ID: !Ref KnowledgeBaseId
          MODEL_ARN: !Ref ModelArn

      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:Retrieve
                - bedrock:RetrieveAndGenerate
                - bedrock:GetKnowledgeBase
                - bedrock:InvokeModel
              Resource: "*"

      Events:
        RagEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref RagApi
            Path: /api/rag
            Method: post

Outputs:
  ApiUrl:
    Value: !Sub "https://${RagApi}.execute-api.${AWS::Region}.amazonaws.com/prod/api/rag"
